### PR TITLE
Audit argument checks

### PR DESCRIPTION
**Pull request by rosatolen**
This pull request adds the audit-argument-checks system to sandforms. This package will automatically check to see that we are using input validation whenever we have arguments in our Meteor.publish and Meteor.methods calls.

Anyone care to mongo inject some objects for QA? ;)

Adding the auditing package also caused the async tests with authorization and permission to fail. Removing async calls and the setup fixtures caused the tests to pass. Not the nicest solution, but it did work. This also resulted in a heavy delete of the test helper code because the changes resulted in it not being used anywhere. If you have suggestions for a better solution to the test failures, let me know. 

We still have a lot to do before we can publish to the app market tho, and this was the quickest solution.

### CODE REVIEW

**Comment by jacksingleton** [comment]
Unfortunately we need the done calls.

What those calls do is make sure that the test doesn't finish before the assertions are called as the assertions are happening in callbacks. So removing them means that the assertions never get called, and none of the tests will ever fail.

We also need some way of setting up the data that the tests assert on... and that's currently done by setupFixtures. This could definitely be improved, but something has to do it.

If you have time I'm down to pair on this tomorrow!

**Comment by rosatolen** [comment]
I'm not sure I will be available tomorrow :( I'm still resting from having my tooth removed and when I walk around, I feel dizzy and overwhelmed.

I undid the removal of the done calls. Feel free to pick it up if you have an idea of what kind of data is needed to get the tests to pass.

**Comment by jacksingleton** [comment]
Oh! Right! NP I'll let you know if I get to work on it tomorrow then.

**Comment by jacksingleton** [comment]
Merged! just had to add one more check. Nice work Rosalie :)

**Pull request merged**
