### PR TITLE
Submit answers

### PR DESCRIPTION
**Pull request by jacksingleton**
This completes the walking skeleton!

It adds a "Submit Answers" screen, and displays all the submitted answers on the responses page.

### CODE REVIEW

**Comment by rosatolen** [comment]
YAAAY! Could you use some sample real questions and answers? That would make the tests easier to read.

**Comment by rosatolen** [comment]
Also I don't have write access. :D Elevation of privilege please Jack! :dancer:

**Comment by yakiradixon** [comment]
Hooray for the walking skeleton! :skull: 

I'm thinking we should rename answersArray to answers in the spec for submissions so we're not referencing the data structure. 

Also, there's a bug right now that renders empty text field submissions as questions. Do we want to fix this as a part of this pull request or open a bug?

**Comment by jacksingleton** [comment]
Thanks for looking at this so quickly @yakiradixon and @rosatolen!

> Elevation of privilege please Jack!

Sent you an invite.

> Could you use some sample real questions and answers?
> 
> I'm thinking we should rename answersArray to answers in the spec for submissions so we're not referencing the data structure.

Done!

> Also, there's a bug right now that renders empty text field submissions as questions. Do we want to fix this as a part of this pull request or open a bug?

Nice catch, let's add a card to Trello. Want to write it up?

**Pull request merged**
