### PR TITLE
Back to jasmine!

### PR DESCRIPTION
**Pull request by jacksingleton**
Port our mocha test suite back to jasmine

The jasmine meteor package seems to be much better maintained than mocha (and is also maintained by the maintainer of meteor-velocity)

### CODE REVIEW

**Comment by rosatolen** [comment]
Port looks good! Dunno why the first time test.sh runs, the tests hang for 2 minutes. After that first go, it's fast, probably because of some caching.

**Comment by rosatolen** [comment]
I'm going to delete this thing because we don't need to hoard branches...

**Comment by MFAnderson** [comment]
@rosatolen that's [Velocity](https://github.com/meteor-velocity/velocity) causing that. It does first time setup to speed up subsequent runs. I'd actually be a happy camper if there was an alternative way of running it, because the first time cost currently gets incurred on every CI build.

**Comment by jacksingleton** [comment]
Nice thanks.

**Pull request merged**
